//! Color-space implementations. One module per space.

mod a98;
mod cubehelix;
pub(crate) mod dlab;
mod dlch;
mod hpluv;
mod hsi;
mod hsl;
pub(crate) mod hsluv;
mod hsv;
mod hwb;
mod itp;
mod jab;
mod jch;
mod lab;
mod lab65;
mod lch;
mod lch65;
mod lchuv;
mod lrgb;
pub(crate) mod luv;
mod okhsl;
pub(crate) mod okhsl_helpers;
mod okhsv;
mod oklab;
mod oklch;
mod p3;
mod prophoto;
mod rec2020;
mod rgb;
mod xyb;
mod xyz50;
mod xyz65;
mod yiq;

pub use a98::A98;
pub use cubehelix::Cubehelix;
pub use dlab::Dlab;
pub use dlch::Dlch;
pub use hpluv::Hpluv;
pub use hsi::Hsi;
pub use hsl::Hsl;
pub use hsluv::Hsluv;
pub use hsv::Hsv;
pub use hwb::Hwb;
pub use itp::Itp;
pub use jab::Jab;
pub use jch::Jch;
pub use lab::Lab;
pub use lab65::Lab65;
pub use lch::Lch;
pub use lch65::Lch65;
pub use lchuv::Lchuv;
pub use lrgb::LinearRgb;
pub use luv::Luv;
pub use okhsl::Okhsl;
pub use okhsv::Okhsv;
pub use oklab::Oklab;
pub use oklch::Oklch;
pub use p3::P3;
pub use prophoto::ProphotoRgb;
pub use rec2020::Rec2020;
pub use rgb::Rgb;
pub use xyb::Xyb;
pub use xyz50::Xyz50;
pub use xyz65::Xyz65;
pub use yiq::Yiq;
