//! Color-space implementations. One module per space.

mod a98;
mod cubehelix;
pub(crate) mod dlab;
mod dlch;
mod hsl;
mod hsv;
mod hwb;
mod jab;
mod jch;
mod lab;
mod lch;
mod lrgb;
mod oklab;
mod oklch;
mod p3;
mod prophoto;
mod rec2020;
mod rgb;
mod xyz50;
mod xyz65;
mod yiq;

pub use a98::A98;
pub use cubehelix::Cubehelix;
pub use dlab::Dlab;
pub use dlch::Dlch;
pub use hsl::Hsl;
pub use hsv::Hsv;
pub use hwb::Hwb;
pub use jab::Jab;
pub use jch::Jch;
pub use lab::Lab;
pub use lch::Lch;
pub use lrgb::LinearRgb;
pub use oklab::Oklab;
pub use oklch::Oklch;
pub use p3::P3;
pub use prophoto::ProphotoRgb;
pub use rec2020::Rec2020;
pub use rgb::Rgb;
pub use xyz50::Xyz50;
pub use xyz65::Xyz65;
pub use yiq::Yiq;
